config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/finances")
  devise_for :users

  # Finances Routes - Home
  get "/finances", to: "finances/home#index", as: "finances_home"

  resources :family_groups, only: [ :index, :new, :create ] do
    post :add_user, on: :member
  end

  # Dashboard
  get "/finances/:family_group_id/dashboard", to: "finances/dashboards#show", as: "finances_dashboard"

  # Budgets Routes
  get "/finances/:family_group_id/budgets", to: "finances/budgets#index", as: "finances_budgets"
  get "/finances/:family_group_id/budget/new", to: "finances/budgets#new", as: "new_finances_budget"
  get "/finances/:family_group_id/budget/edit", to: "finances/budgets#edit", as: "edit_finances_budgets"
  patch "/finances/:family_group_id/budget/update/:month", to: "finances/budgets#update", as: "update_for_month"
  get "/finances/:family_group_id/budget/:month", to: "finances/budgets#show", as: "finances_budget_show"
  post "/finances/:family_group_id/budget", to: "finances/budgets#create", as: "create_finances_budget"

  # Consolidated Routes
  get "/finances/:family_group_id/consolidated", to: "finances/consolidated#index", as: "finances_consolidated"

  # Transactions Routes
  get "/finances/:family_group_id/transactions", to: "finances/transactions#index", as: "finances_transactions"
  get "/finances/:family_group_id/transactions/new/:category_type", to: "finances/transactions#new_by_category_type", as: "new_by_category_type"
  post "/finances/:family_group_id/transactions", to: "finances/transactions#create", as: "create_finances_transaction"
  get "/finances/:family_group_id/transactions/:id/edit", to: "finances/transactions#edit", as: "edit_finances_transaction"
  patch "/finances/:family_group_id/transactions/:id", to: "finances/transactions#update", as: "update_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id", to: "finances/transactions#destroy", as: "destroy_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id/destroy_future", to: "finances/transactions#destroy_future", as: "destroy_future_finances_transaction"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/finances/budgets_controller.rb
class Finances::BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def index
    @months = @family_group.budgets.distinct.pluck(:month).sort.reverse
  end
  def show
    @month = params[:month]
    @budgets = @family_group.budgets.includes(:transaction_category).where(month: @month)

    if @budgets.empty?
      redirect_to finances_budget_path(@family_group), alert: "Nenhum orçamento encontrado para o mês #{@month}."
    else
      @grouped_budgets = @budgets.group_by { |budget| budget.transaction_category.category_type }
    end
  end

  def new
    @month = params[:month] || Date.today.strftime("%Y-%m")

    @grouped_categories = @family_group.transaction_categories.group_by(&:category_type)

    @categories = @family_group.transaction_categories.map do |category|
      Budget.new(transaction_category: category, month: @month, value: 0)
    end
  end

  def create
    budgets = budgets_params.map do |budget_param|
      @family_group.budgets.new(budget_param)
    end

    if budgets.all?(&:save)
      redirect_to finances_budget_path(@family_group), notice: "Orçamentos criados com sucesso!"
    else
      error_messages = budgets.map { |budget| budget.errors.full_messages }.flatten
      flash[:alert] = "Erro ao criar os orçamentos: #{error_messages.join(', ')}"
      @month = params[:month]
      @categories = budgets
      render :new
    end
  end

  def edit
    @current_month = Time.now.strftime("%Y-%m")
    @budgets = @family_group.budgets.where(month: @current_month)

    @grouped_budgets = @budgets.group_by { |budget| budget.transaction_category.category_type }
  end

  def update
    @month = params[:month]
    @budgets = @family_group.budgets.where(month: @month)

    if @budgets.empty?
      redirect_to finances_budget_path(@family_group), alert: "Nenhum orçamento encontrado para o mês #{@month}."
      return
    end

    # Processa os parâmetros de orçamento para atualizar
    success = budgets_params.all? do |budget_param|
      budget = @budgets.find { |b| b.id == budget_param[:id].to_i }
      budget && budget.update(budget_param)
    end

    if success
      redirect_to finances_budget_path(@family_group, month: @month), notice: "Orçamentos atualizados com sucesso!"
    else
      flash.now[:alert] = "Erro ao atualizar os orçamentos. Verifique os campos e tente novamente."
      render :edit
    end
  end


  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end

  def budgets_params
    params.require(:budgets).permit(
      # Permite múltiplos orçamentos, cada um com esses atributos
      budgets: [ :id, :transaction_category_id, :value, :month ]
    )[:budgets].values
  end
end

app/controllers/finances/consolidated_controller.rb
class Finances::ConsolidatedController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def index
    @year = params[:year]&.to_i || Date.today.year
    @service = ConsolidatedDataService.new(@family_group, @year)
    @consolidated_data = @service.call

    @chart_data = prepare_chart_data(@consolidated_data)
  end

  def prepare_chart_data(consolidated_data)
    {
      receitas: (1..12).map { |month| sum_monthly_totals(consolidated_data["Receitas"], month) },
      gastos_fixos: (1..12).map { |month| sum_monthly_totals(consolidated_data["Gastos Fixos"], month) },
      gastos_variaveis: (1..12).map { |month| sum_monthly_totals(consolidated_data["Gastos Variáveis"], month) },
      investimentos: (1..12).map { |month| sum_monthly_totals(consolidated_data["Investimentos"], month) }
    }
  end

  private

  def sum_monthly_totals(category_data, month)
    return 0 unless category_data

    category_data.values.reduce(0) do |sum, subcategory|
      sum + (subcategory[month] || 0)
    end
  end

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end
end

app/controllers/finances/dashboards_controller.rb
class Finances::DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def show
  end

  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end
end

app/controllers/finances/home_controller.rb
class Finances::HomeController < ApplicationController
  before_action :authenticate_user!  # Garante que o usuário esteja autenticado

  def index
    @family_groups = current_user.family_groups
    @current_user = current_user
  end
end

app/controllers/finances/transactions_controller.rb
class Finances::TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group
  before_action :set_transaction, only: [ :show, :edit, :update, :destroy ]
  before_action :set_bank_accounts, only: [ :new_by_category_type, :edit ]
  helper_method :new_url

  CATEGORY_TYPE_MAP = {
    "revenue" => "Receitas",
    "investment" => "Investimentos",
    "fixed-expenses" => "Gastos Fixos",
    "variable-expenses" => "Gastos Variáveis"
  }

  def new_url(params)
    case params
    when "Receitas"
      "revenue"
    when "Investimentos"
      "investment"
    when "Gastos Fixos"
      "fixed-expenses"
    else
      "variable-expenses"
    end
  end

  def index
    if params[:month].present?
      begin
        @month = Date.parse("#{params[:month]}-01")
      rescue ArgumentError => e
        @month = Date.today
      end
    else
      @month = Date.today
    end

    @transactions = @family_group.transactions
    @category_types = CategoryType.all

    if @month
      start_of_month = @month.beginning_of_month
      end_of_month = @month.end_of_month

      @transactions = @transactions.where(month: start_of_month.strftime("%Y-%m")..end_of_month.strftime("%Y-%m"))
    end

    if params[:category_type].present?
      @category_type = params[:category_type] # Captura o parâmetro enviado
      @transactions = @transactions.joins(transaction_category: :category_type)
        .where(category_types: { name: @category_type })
    end

    @totals_by_category_type = CategoryType.all.each_with_object({}) do |category_type, hash|
      total_value = @transactions.joins(:transaction_category)
                                .where(transaction_categories: { category_type_id: category_type.id })
                                .sum(:value)

      hash[category_type.name] = total_value
    end
  end

  def new_by_category_type
    @category_type = CATEGORY_TYPE_MAP[params[:category_type]]

    if @category_type.nil?
      redirect_to finances_transactions_path(@family_group), alert: "Categoria inválida."
      return
    end

    category_type_key = params[:category_type]
    category_type_name = CATEGORY_TYPE_MAP[category_type_key]
    @transaction_categories = TransactionCategory.joins(:category_type)
      .where(category_types: { name: category_type_name })
      .where(family_group_id: @family_group.id)

    @transaction = @family_group.transactions.build
    @month = params[:month] || Date.today.strftime("%Y-%m")

    respond_to do |format|
      format.turbo_stream { render :new_by_category_type }
      format.html { render :new_by_category_type, layout: false }
    end
  end

  def create
    @transaction = @family_group.transactions.build(transaction_params)

    if @transaction.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("transactions-body", partial: "transaction", locals: { transaction: @transaction }),
            turbo_stream.remove("modal-frame"),
            turbo_stream.remove("modal")
          ]
        end
        format.html { redirect_to finances_transactions_path(@family_group), notice: "Transação criada com sucesso." }
      end
    else
      Rails.logger.error @transaction.errors.full_messages.join(", ")
      respond_to do |format|
        format.turbo_stream { render :new_by_category_type }
        format.html { render :new_by_category_type }
      end
    end
  end

  def edit
    @transaction = @family_group.transactions.find(params[:id])
    @transaction_categories = TransactionCategory.joins(:category_type)
      .where(category_types: { id: @transaction.transaction_category.category_type_id })
      .order(:name)

    respond_to do |format|
      format.turbo_stream { render :edit }
      format.html { render :edit }
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to finances_transactions_path(@family_group), notice: "Transação atualizada com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @transaction = @family_group.transactions.find(params[:id])

    if @transaction.subscription
      future_transactions = @family_group.transactions.where("month > ? AND name = ? AND transaction_category_id = ? AND bank_account_id = ?", @transaction.month, @transaction.name, @transaction.transaction_category_id, @transaction.bank_account_id)
      future_transactions.destroy_all
    end

    @transaction.destroy
    respond_to do |format|
      format.turbo_stream { redirect_to finances_transactions_path(@family_group), notice: "Transação excluída com sucesso." }
      format.html { redirect_to finances_transactions_path(@family_group), notice: "Transação excluída com sucesso." }
    end
  end

  def destroy_future
    @transaction = @family_group.transactions.find(params[:id])

    if @transaction.subscription
      future_transactions = @family_group.transactions.where("month > ? AND name = ? AND transaction_category_id = ? AND bank_account_id = ?", @transaction.month, @transaction.name, @transaction.transaction_category_id, @transaction.bank_account_id)
      future_transactions.destroy_all
    end

    respond_to do |format|
      format.turbo_stream { redirect_to finances_transactions_path(@family_group), notice: "Faturas futuras excluídas com sucesso." }
      format.html { redirect_to finances_transactions_path(@family_group), notice: "Faturas futuras excluídas com sucesso." }
    end
  end

  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end

  def set_bank_accounts
    @bank_accounts = @family_group.users.joins(:bank_accounts).select("bank_accounts.*")
  end

  def set_transaction
    @transaction = @family_group.transactions.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(
      :name,
      :value,
      :month,
      :subscription,
      :number_of_installments,
      :current_installment,
      :transaction_category_id,
      :bank_account_id,
      :family_group_id
    )
  end
end

app/views/finances/consolidated/_hero.html.erb
<div class="hero-card bg-white rounded col-span-12 px-5 py-4 flex items-center">
  <div class="principal-content flex-1">
    <div class="flex text-base text-gray-400 mb-2 gap-1">
      <svg  xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-hand-coins"><path d="M11 15h2a2 2 0 1 0 0-4h-3c-.6 0-1.1.2-1.4.6L3 17"/><path d="m7 21 1.6-1.4c.3-.4.8-.6 1.4-.6h4c1.1 0 2.1-.4 2.8-1.2l4.6-4.4a2 2 0 0 0-2.75-2.91l-4.2 3.9"/><path d="m2 16 6 6"/><circle cx="16" cy="9" r="2.9"/><circle cx="6" cy="5" r="3"/></svg>
      <p>
        Consolidado:
      </p>
    </div>
    <h1 class="font-black text-3xl text-gray-700">
      <%= @family_group.name %>
    </h1>
  </div>

  <div class="filter">
    <%= form_with url: finances_consolidated_path(@family_group), method: :get, local: true, data: { turbo_frame: "transactions" } do |form| %>
      <%= 
        select_tag :year, 
        options_for_select((Date.today.year - 5..Date.today.year).to_a.reverse, params[:year] || Date.today.year), 
        class: "form-control",
        onchange: "this.form.submit()"
      %>
    <% end %>
  </div>
</div>

app/views/finances/consolidated/index.html.erb
<div class="individual-content grid gap-x-3	grid-cols-12 mb-16">
  <%= render 'hero' %>

  <section class="bg-white rounded col-span-12 flex justify-center items-center mt-6 h-[380px]">    
    <!-- Spinner -->
    <div id="loading-spinner" class="py-10">
      <%= image_tag("Animation - 1733439059325.gif", class: "max-w-60 h-60") %>
    </div>
    
    <!-- Chart -->
    <canvas id="consolidatedChart" class="hidden" width="370" height="100"></canvas>
    <script type="application/json" id="chart-data">
      <%= @chart_data.to_json.html_safe %>
    </script>
  </section>

  <!--<code class="language-json">-->
    <%#= @chart_data.to_json %>
  <!--</code>-->

  <section class="col-span-12">
    <div class="flex flex-col mt-6 w-full">
      <div class="overflow-x-auto">
        <div class="inline-block min-w-full align-middle">
          <div class="overflow-hidden border border-gray-200 md:rounded-lg">
            <%= turbo_frame_tag "consolidated_data" do %>
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">
                      Categoria
                    </th>
                    <% (1..12).each do |month| %>
                      <th scope="col" class="px-4 py-3.5 text-sm font-black text-left rtl:text-right text-gray-500">
                        <%= Date::ABBR_MONTHNAMES[month] %>
                      </th>
                    <% end %>
                    <th scope="col" class="px-4 py-3.5 text-sm font-black text-left rtl:text-right text-gray-500">
                      Total
                    </th>
                    <th scope="col" class="px-4 py-3.5 text-sm font-black text-left rtl:text-right text-gray-500">
                      % RL
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <% @consolidated_data.each do |category_type, categories| %>
                    <!-- Agrupamento por Tipo de Categoria -->
                    <tr>
                      <td class="px-2 py-2 text-sm font-bold whitespace-nowrap bg-gray-100" colspan="15">
                        <%= category_type %>
                      </td>
                    </tr>

                    <% categories.each do |category_name, monthly_values| %>
                      <!-- Detalhes de cada Categoria -->
                        <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
                          <p class="text-sm text-gray-600 font-bold">
                            <%= category_name %>
                          </p>
                        </td>
                        <% (1..12).each do |month| %>
                          <td class="px-4 py-2 text-sm font-medium whitespace-nowrap">
                            <p class="text-sm font-normal text-gray-600 cursor-pointer">
                              <%= monthly_values[month] ? number_to_currency(monthly_values[month], locale: 'pt-BR') : "-" %>
                            </p>
                          </td>
                        <% end %>
                        <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
                          <p class="text-sm font-bold text-gray-600 cursor-pointer">
                            <%= number_to_currency(monthly_values[:total], locale: 'pt-BR') %>
                          </p>
                        </td>
                        <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
                          <p class="text-sm font-bold text-gray-600 cursor-pointer">
                            <%= number_to_percentage(monthly_values[:percentage], precision: 2) %>
                          </p>
                        </td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
                <tfoot>
                  <tr class="bg-gray-500 text-white font-bold">
                    <th class="px-4 py-2 text-sm whitespace-nowrap text-left">
                      Total Geral
                    </th>
                    <% (1..12).each do |month| %>
                      <th class="px-4 py-2 text-sm whitespace-nowrap text-left">
                        <%= number_to_currency(
                          @consolidated_data.sum do |category_type, categories|
                            categories.sum do |category_name, values|
                              # Verificar se o tipo de categoria é Receita, se sim, soma, se não, subtrai
                              if category_type == "Receitas"
                                values[month].to_f
                              else
                                -values[month].to_f # Subtrai para Investimentos, Gastos Fixos, e Gastos Variáveis
                              end
                            end
                          end, locale: 'pt-BR'                          
                        ) %>
                      </th>
                    <% end %>
                    <th class="px-4 py-2 text-sm whitespace-nowrap text-left">
                      <%= number_to_currency(
                        @consolidated_data.sum do |category_type, categories|
                          categories.sum do |category_name, values|
                            # Verificar se o tipo de categoria é Receita, se sim, soma, se não, subtrai
                            if category_type == "Receitas"
                              values[:total].to_f
                            else
                              -values[:total].to_f # Subtrai para Investimentos, Gastos Fixos, e Gastos Variáveis
                            end
                          end
                        end, locale: 'pt-BR'
                      ) %>
                    </th>
                    <th class="px-4 py-2 text-sm whitespace-nowrap text-left">
                      <%= number_to_percentage(
                        @consolidated_data.sum do |category_type, categories|
                          categories.sum do |category_name, values|
                            # Verificar se o tipo de categoria é Receita, se sim, soma, se não, subtrai
                            if category_type == "Receitas"
                              values[:percentage].to_f
                            else
                              -values[:percentage].to_f # Subtrai para Investimentos, Gastos Fixos, e Gastos Variáveis
                            end
                          end
                        end / 12, precision: 2
                      ) %>
                    </th>
                  </tr>
                </tfoot>
              </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>