config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/finances")
  devise_for :users

  # Finances Routes - Home
  get "/finances", to: "finances/home#index", as: "finances_home"

  resources :family_groups, only: [ :index, :new, :create ] do
    post :add_user, on: :member
  end

  # Dashboard
  get "/finances/:family_group_id/dashboard", to: "finances/dashboards#show", as: "finances_dashboard"

  # Budgets Routes
  get "/finances/:family_group_id/budgets", to: "finances/budgets#index", as: "finances_budgets"
  get "/finances/:family_group_id/budget/new", to: "finances/budgets#new", as: "new_finances_budget"
  get "/finances/:family_group_id/budget/edit", to: "finances/budgets#edit", as: "edit_finances_budgets"
  patch "/finances/:family_group_id/budget/update/:month", to: "finances/budgets#update", as: "update_for_month"
  get "/finances/:family_group_id/budget/:month", to: "finances/budgets#show", as: "finances_budget_show"
  post "/finances/:family_group_id/budget", to: "finances/budgets#create", as: "create_finances_budget"

  # Consolidated Routes
  get "/finances/:family_group_id/consolidated", to: "finances/consolidated#index", as: "finances_consolidated"

  # Transactions Routes
  get "/finances/:family_group_id/transactions", to: "finances/transactions#index", as: "finances_transactions"
  get "/finances/:family_group_id/transactions/new/:category_type", to: "finances/transactions#new_by_category_type", as: "new_by_category_type"
  post "/finances/:family_group_id/transactions", to: "finances/transactions#create", as: "create_finances_transaction"
  get "/finances/:family_group_id/transactions/:id/edit", to: "finances/transactions#edit", as: "edit_finances_transaction"
  patch "/finances/:family_group_id/transactions/:id", to: "finances/transactions#update", as: "update_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id", to: "finances/transactions#destroy", as: "destroy_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id/destroy_future", to: "finances/transactions#destroy_future", as: "destroy_future_finances_transaction"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/budget.rb
class Budget < ApplicationRecord
  # Associações
  belongs_to :transaction_category
  belongs_to :family_group

  # Validações
  validates :value, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :month, presence: true, format: { with: /\A\d{4}-\d{2}\z/, message: "Formato deve ser YYYY-MM" }
  validates :transaction_category, presence: true
  validates :family_group, presence: true

  # Validação de unicidade para garantir que não existam orçamentos duplicados para o mesmo family_group, transaction_category e month
  validates :transaction_category, uniqueness: { scope: [ :family_group, :month ], message: "Já existe um orçamento para essa categoria e mês" }
end

app/controllers/finances/budgets_controller.rb
class Finances::BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def index
    @months = @family_group.budgets.distinct.pluck(:month).sort.reverse
  end
  def show
    @month = params[:month]
    @budgets = @family_group.budgets.includes(:transaction_category).where(month: @month)

    if @budgets.empty?
      redirect_to finances_budget_path(@family_group), alert: "Nenhum orçamento encontrado para o mês #{@month}."
    else
      @grouped_budgets = @budgets.group_by { |budget| budget.transaction_category.category_type }
    end
  end

  def new
    @month = params[:month] || Date.today.strftime("%Y-%m")

    @grouped_categories = @family_group.transaction_categories.group_by(&:category_type)

    @categories = @family_group.transaction_categories.map do |category|
      Budget.new(transaction_category: category, month: @month, value: 0)
    end
  end

  def create
    budgets = budgets_params.map do |budget_param|
      @family_group.budgets.new(budget_param)
    end

    if budgets.all?(&:save)
      redirect_to finances_budget_path(@family_group), notice: "Orçamentos criados com sucesso!"
    else
      error_messages = budgets.map { |budget| budget.errors.full_messages }.flatten
      flash[:alert] = "Erro ao criar os orçamentos: #{error_messages.join(', ')}"
      @month = params[:month]
      @categories = budgets
      render :new
    end
  end

  def edit
    @current_month = Time.now.strftime("%Y-%m")
    @budgets = @family_group.budgets.where(month: @current_month)

    @grouped_budgets = @budgets.group_by { |budget| budget.transaction_category.category_type }
  end

  def update
    @month = params[:month]
    @budgets = @family_group.budgets.where(month: @month)

    if @budgets.empty?
      redirect_to finances_budget_path(@family_group), alert: "Nenhum orçamento encontrado para o mês #{@month}."
      return
    end

    # Processa os parâmetros de orçamento para atualizar
    success = budgets_params.all? do |budget_param|
      budget = @budgets.find { |b| b.id == budget_param[:id].to_i }
      budget && budget.update(budget_param)
    end

    if success
      redirect_to finances_budget_path(@family_group, month: @month), notice: "Orçamentos atualizados com sucesso!"
    else
      flash.now[:alert] = "Erro ao atualizar os orçamentos. Verifique os campos e tente novamente."
      render :edit
    end
  end


  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end

  def budgets_params
    params.require(:budgets).permit(
      # Permite múltiplos orçamentos, cada um com esses atributos
      budgets: [ :id, :transaction_category_id, :value, :month ]
    )[:budgets].values
  end
end

app/controllers/finances/consolidated_controller.rb
class Finances::ConsolidatedController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def index
    @year = params[:year]&.to_i || Date.today.year
    @service = ConsolidatedDataService.new(@family_group, @year)
    @consolidated_data = @service.call

    @chart_data = prepare_chart_data(@consolidated_data)
  end

  def prepare_chart_data(consolidated_data)
    {
      receitas: (1..12).map { |month| sum_monthly_totals(consolidated_data["Receitas"], month) },
      gastos_fixos: (1..12).map { |month| sum_monthly_totals(consolidated_data["Gastos Fixos"], month) },
      gastos_variaveis: (1..12).map { |month| sum_monthly_totals(consolidated_data["Gastos Variáveis"], month) },
      investimentos: (1..12).map { |month| sum_monthly_totals(consolidated_data["Investimentos"], month) }
    }
  end

  private

  def sum_monthly_totals(category_data, month)
    return 0 unless category_data

    category_data.values.reduce(0) do |sum, subcategory|
      sum + (subcategory[month] || 0)
    end
  end

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end
end

app/controllers/finances/dashboards_controller.rb
class Finances::DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def show
  end

  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end
end

app/controllers/finances/home_controller.rb
class Finances::HomeController < ApplicationController
  before_action :authenticate_user!  # Garante que o usuário esteja autenticado

  def index
    @family_groups = current_user.family_groups
    @current_user = current_user
  end
end

app/controllers/finances/transactions_controller.rb
class Finances::TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group
  before_action :set_transaction, only: [ :show, :edit, :update, :destroy ]
  before_action :set_bank_accounts, only: [ :new_by_category_type, :edit ]
  helper_method :new_url

  CATEGORY_TYPE_MAP = {
    "revenue" => "Receitas",
    "investment" => "Investimentos",
    "fixed-expenses" => "Gastos Fixos",
    "variable-expenses" => "Gastos Variáveis"
  }

  def new_url(params)
    case params
    when "Receitas"
      "revenue"
    when "Investimentos"
      "investment"
    when "Gastos Fixos"
      "fixed-expenses"
    else
      "variable-expenses"
    end
  end

  def index
    if params[:month].present?
      begin
        @month = Date.parse("#{params[:month]}-01")
      rescue ArgumentError => e
        @month = Date.today
      end
    else
      @month = Date.today
    end

    @transactions = @family_group.transactions
    @category_types = CategoryType.all

    if @month
      start_of_month = @month.beginning_of_month
      end_of_month = @month.end_of_month

      @transactions = @transactions.where(month: start_of_month.strftime("%Y-%m")..end_of_month.strftime("%Y-%m"))
    end

    if params[:category_type].present?
      @category_type = params[:category_type] # Captura o parâmetro enviado
      @transactions = @transactions.joins(transaction_category: :category_type)
        .where(category_types: { name: @category_type })
    end

    @totals_by_category_type = CategoryType.all.each_with_object({}) do |category_type, hash|
      total_value = @transactions.joins(:transaction_category)
                                .where(transaction_categories: { category_type_id: category_type.id })
                                .sum(:value)

      hash[category_type.name] = total_value
    end
  end

  def new_by_category_type
    @category_type = CATEGORY_TYPE_MAP[params[:category_type]]

    if @category_type.nil?
      redirect_to finances_transactions_path(@family_group), alert: "Categoria inválida."
      return
    end

    category_type_key = params[:category_type]
    category_type_name = CATEGORY_TYPE_MAP[category_type_key]
    @transaction_categories = TransactionCategory.joins(:category_type)
      .where(category_types: { name: category_type_name })
      .where(family_group_id: @family_group.id)

    @transaction = @family_group.transactions.build
    @month = params[:month] || Date.today.strftime("%Y-%m")

    respond_to do |format|
      format.turbo_stream { render :new_by_category_type }
      format.html { render :new_by_category_type, layout: false }
    end
  end

  def create
    @transaction = @family_group.transactions.build(transaction_params)

    if @transaction.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("transactions-body", partial: "transaction", locals: { transaction: @transaction }),
            turbo_stream.remove("modal-frame"),
            turbo_stream.remove("modal")
          ]
        end
        format.html { redirect_to finances_transactions_path(@family_group), notice: "Transação criada com sucesso." }
      end
    else
      Rails.logger.error @transaction.errors.full_messages.join(", ")
      respond_to do |format|
        format.turbo_stream { render :new_by_category_type }
        format.html { render :new_by_category_type }
      end
    end
  end

  def edit
    @transaction = @family_group.transactions.find(params[:id])
    @transaction_categories = TransactionCategory.joins(:category_type)
      .where(category_types: { id: @transaction.transaction_category.category_type_id })
      .order(:name)

    respond_to do |format|
      format.turbo_stream { render :edit }
      format.html { render :edit }
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to finances_transactions_path(@family_group), notice: "Transação atualizada com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @transaction = @family_group.transactions.find(params[:id])

    if @transaction.subscription
      future_transactions = @family_group.transactions.where("month > ? AND name = ? AND transaction_category_id = ? AND bank_account_id = ?", @transaction.month, @transaction.name, @transaction.transaction_category_id, @transaction.bank_account_id)
      future_transactions.destroy_all
    end

    @transaction.destroy
    respond_to do |format|
      format.turbo_stream { redirect_to finances_transactions_path(@family_group), notice: "Transação excluída com sucesso." }
      format.html { redirect_to finances_transactions_path(@family_group), notice: "Transação excluída com sucesso." }
    end
  end

  def destroy_future
    @transaction = @family_group.transactions.find(params[:id])

    if @transaction.subscription
      future_transactions = @family_group.transactions.where("month > ? AND name = ? AND transaction_category_id = ? AND bank_account_id = ?", @transaction.month, @transaction.name, @transaction.transaction_category_id, @transaction.bank_account_id)
      future_transactions.destroy_all
    end

    respond_to do |format|
      format.turbo_stream { redirect_to finances_transactions_path(@family_group), notice: "Faturas futuras excluídas com sucesso." }
      format.html { redirect_to finances_transactions_path(@family_group), notice: "Faturas futuras excluídas com sucesso." }
    end
  end

  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end

  def set_bank_accounts
    @bank_accounts = @family_group.users.joins(:bank_accounts).select("bank_accounts.*")
  end

  def set_transaction
    @transaction = @family_group.transactions.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(
      :name,
      :value,
      :month,
      :subscription,
      :number_of_installments,
      :current_installment,
      :transaction_category_id,
      :bank_account_id,
      :family_group_id
    )
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/finances/budgets/_hero.html.erb
<div class="hero-card bg-white rounded col-span-12 px-5 py-4">
  <div class="flex text-base text-gray-400 mb-2 gap-1">
    <svg class="w-5 h-6" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-notepad-text"><path d="M8 2v4"/><path d="M12 2v4"/><path d="M16 2v4"/><rect width="16" height="18" x="4" y="4" rx="2"/><path d="M8 10h6"/><path d="M8 14h8"/><path d="M8 18h5"/></svg>
    <p>
      Orçamento:
    </p>
  </div>
  <h1 class="font-black text-3xl text-gray-700">
    <%= @family_group.name %>
  </h1>
</div>

app/views/finances/budgets/edit.html.erb
<h1>Editar Orçamento do Mês: <%= @month %> - <%= @family_group.name %></h1>

<%= form_with(url: finances_budgets_path(@family_group, month: @month), method: :patch) do %>
  <table>
    <thead>
      <tr>
        <th>Categoria</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <% @grouped_budgets.each do |category_type, budgets| %>
        <tr>
          <th colspan="2" class="category-type-header"><%= category_type.name %></th>
        </tr>
        
        <% budgets.each_with_index do |budget, index| %>
          <tr>
            <td>
              <%= budget.transaction_category.name %>
              <%= hidden_field_tag "budgets[#{index}][id]", budget.id %>
            </td>
            <td>
              <%= number_field_tag "budgets[#{index}][value]", budget.value, min: 0, step: 0.01, class: "form-control" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= submit_tag "Salvar Orçamentos", class: "btn btn-primary" %>
    <%= link_to "Cancelar", finances_budgets_path(@family_group), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/finances/budgets/index.html.erb
<div class="individual-content grid gap-x-3	grid-cols-12">
  <%= render 'hero' %>

  <section class="col-span-12">
    <% if @months.any? %>
      <table>
        <tbody>
          <% @months.each do |month| %>
            <tr>
              <td>
                <%= link_to l(Date.parse("#{month}-01"), format: :long), finances_budget_show_path(@family_group, month: month) %>
              </td>
              <td>
                <p>
                  2020
                </p>
              </td>
              <td>
                <p>
                  $35,000
                </p>
              </td>
              <td>
                <p>
                  New York, USA
                </p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Não há orçamentos criados ainda.</p>
    <% end %>
    <%= link_to 'Novo Orçamento', new_finances_budget_path(@family_group) %>
  </section>
</div>

app/views/finances/budgets/new.html.erb
<h1>Criar Orçamento</h1>

<%= form_with(url: create_finances_budget_path(@family_group), method: :post) do %>
  <div>
    <label for="month">Mês</label>
    <%= month_field_tag :month, @month, class: "form-control", min: Date.today.strftime("%Y-%m") %>
  </div>

  <table>
    <thead>
      <tr>
        <th>Tipo de Categoria</th>
        <th>Categoria</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <% @grouped_categories.each do |category_type, categories| %>
        <tr>
          <td colspan="3"><strong><%= category_type.name %></strong></td>
        </tr>
        <% categories.each_with_index do |category, index| %>
          <tr>
            <td></td>
            <td>
              <%= category.name %>
              <%= hidden_field_tag "budgets[#{index}][transaction_category_id]", category.id %>
            </td>
            <td>
              <%= number_field_tag "budgets[#{index}][value]", 0, min: 0, step: 0.01, class: "form-control" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= submit_tag "Criar Orçamentos", class: "btn btn-primary" %>
    <%= link_to "Cancelar", finances_budgets_path(@family_group), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/finances/budgets/show.html.erb
<h1>Orçamentos para <%= l(Date.parse("#{@month}-01"), format: :long) %></h1>

<% if @grouped_budgets.present? %>
  <table>
    <thead>
      <tr>
        <th>Categoria</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <% @grouped_budgets.each do |category_type, budgets| %>
        <tr>
          <td colspan="2"><strong><%= category_type.name %></strong></td>
        </tr>
        <% budgets.each do |budget| %>
          <tr>
            <td><%= budget.transaction_category.name %></td>
            <td><%= number_to_currency(budget.value) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= link_to "Editar Orçamentos do Mês", edit_finances_budgets_path(@family_group, month: @month), class: "btn btn-primary" %>
  </div>
<% else %>
  <p>Nenhum orçamento disponível para o mês selecionado.</p>
<% end %>

<%= link_to "Voltar", finances_budgets_path(@family_group), class: "btn btn-secondary" %>