config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/finances")
  devise_for :users

  # Finances Routes - Home
  get "/finances", to: "finances/home#index", as: "finances_home"

  resources :family_groups, only: [ :index, :new, :create ] do
    post :add_user, on: :member
  end

  # Dashboard
  get "/finances/:family_group_id/dashboard", to: "finances/dashboards#show", as: "finances_dashboard"

  # Budgets Routes
  get "/finances/:family_group_id/budgets", to: "finances/budgets#index", as: "finances_budgets"
  get "/finances/:family_group_id/budget/new", to: "finances/budgets#new", as: "new_finances_budget"
  get "/finances/:family_group_id/budget/edit", to: "finances/budgets#edit", as: "edit_finances_budgets"
  patch "/finances/:family_group_id/budget/update/:month", to: "finances/budgets#update", as: "update_for_month"
  get "/finances/:family_group_id/budget/:month", to: "finances/budgets#show", as: "finances_budget_show"
  post "/finances/:family_group_id/budget", to: "finances/budgets#create", as: "create_finances_budget"

  # Consolidated Routes
  get "/finances/:family_group_id/consolidated", to: "finances/consolidated#index", as: "finances_consolidated"

  # Transactions Routes
  get "/finances/:family_group_id/transactions", to: "finances/transactions#index", as: "finances_transactions"
  get "/finances/:family_group_id/transactions/new/:category_type", to: "finances/transactions#new_by_category_type", as: "new_by_category_type"
  post "/finances/:family_group_id/transactions", to: "finances/transactions#create", as: "create_finances_transaction"
  get "/finances/:family_group_id/transactions/:id/edit", to: "finances/transactions#edit", as: "edit_finances_transaction"
  patch "/finances/:family_group_id/transactions/:id", to: "finances/transactions#update", as: "update_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id", to: "finances/transactions#destroy", as: "destroy_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id/destroy_future", to: "finances/transactions#destroy_future", as: "destroy_future_finances_transaction"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/finances/budgets_controller.rb
class Finances::BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def index
    @months = @family_group.budgets.distinct.pluck(:month).sort.reverse
  end
  def show
    @month = params[:month]
    @budgets = @family_group.budgets.includes(:transaction_category).where(month: @month)

    if @budgets.empty?
      redirect_to finances_budget_path(@family_group), alert: "Nenhum orçamento encontrado para o mês #{@month}."
    else
      @grouped_budgets = @budgets.group_by { |budget| budget.transaction_category.category_type }
    end
  end

  def new
    @month = params[:month] || Date.today.strftime("%Y-%m")

    @grouped_categories = @family_group.transaction_categories.group_by(&:category_type)

    @categories = @family_group.transaction_categories.map do |category|
      Budget.new(transaction_category: category, month: @month, value: 0)
    end
  end

  def create
    budgets = budgets_params.map do |budget_param|
      @family_group.budgets.new(budget_param)
    end

    if budgets.all?(&:save)
      redirect_to finances_budget_path(@family_group), notice: "Orçamentos criados com sucesso!"
    else
      error_messages = budgets.map { |budget| budget.errors.full_messages }.flatten
      flash[:alert] = "Erro ao criar os orçamentos: #{error_messages.join(', ')}"
      @month = params[:month]
      @categories = budgets
      render :new
    end
  end

  def edit
    @current_month = Time.now.strftime("%Y-%m")
    @budgets = @family_group.budgets.where(month: @current_month)

    @grouped_budgets = @budgets.group_by { |budget| budget.transaction_category.category_type }
  end

  def update
    @month = params[:month]
    @budgets = @family_group.budgets.where(month: @month)

    if @budgets.empty?
      redirect_to finances_budget_path(@family_group), alert: "Nenhum orçamento encontrado para o mês #{@month}."
      return
    end

    # Processa os parâmetros de orçamento para atualizar
    success = budgets_params.all? do |budget_param|
      budget = @budgets.find { |b| b.id == budget_param[:id].to_i }
      budget && budget.update(budget_param)
    end

    if success
      redirect_to finances_budget_path(@family_group, month: @month), notice: "Orçamentos atualizados com sucesso!"
    else
      flash.now[:alert] = "Erro ao atualizar os orçamentos. Verifique os campos e tente novamente."
      render :edit
    end
  end


  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end

  def budgets_params
    params.require(:budgets).permit(
      # Permite múltiplos orçamentos, cada um com esses atributos
      budgets: [ :id, :transaction_category_id, :value, :month ]
    )[:budgets].values
  end
end

app/controllers/finances/consolidated_controller.rb
class Finances::ConsolidatedController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def index
    @year = params[:year]&.to_i || Date.today.year
    @service = ConsolidatedDataService.new(@family_group, @year)
    @consolidated_data = @service.call

    @chart_data = prepare_chart_data(@consolidated_data)
  end

  def prepare_chart_data(consolidated_data)
    {
      receitas: (1..12).map { |month| sum_monthly_totals(consolidated_data["Receitas"], month) },
      gastos_fixos: (1..12).map { |month| sum_monthly_totals(consolidated_data["Gastos Fixos"], month) },
      gastos_variaveis: (1..12).map { |month| sum_monthly_totals(consolidated_data["Gastos Variáveis"], month) },
      investimentos: (1..12).map { |month| sum_monthly_totals(consolidated_data["Investimentos"], month) }
    }
  end

  private

  def sum_monthly_totals(category_data, month)
    return 0 unless category_data

    category_data.values.reduce(0) do |sum, subcategory|
      sum + (subcategory[month] || 0)
    end
  end

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end
end

app/controllers/finances/dashboards_controller.rb
class Finances::DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group

  def show
  end

  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end
end

app/controllers/finances/home_controller.rb
class Finances::HomeController < ApplicationController
  before_action :authenticate_user!  # Garante que o usuário esteja autenticado

  def index
    @family_groups = current_user.family_groups
    @current_user = current_user
  end
end

app/controllers/finances/transactions_controller.rb
class Finances::TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_and_authorize_family_group
  before_action :set_transaction, only: [ :show, :edit, :update, :destroy ]
  before_action :set_bank_accounts, only: [ :new_by_category_type, :edit ]
  helper_method :new_url

  CATEGORY_TYPE_MAP = {
    "revenue" => "Receitas",
    "investment" => "Investimentos",
    "fixed-expenses" => "Gastos Fixos",
    "variable-expenses" => "Gastos Variáveis"
  }

  def new_url(params)
    case params
    when "Receitas"
      "revenue"
    when "Investimentos"
      "investment"
    when "Gastos Fixos"
      "fixed-expenses"
    else
      "variable-expenses"
    end
  end

  def index
    if params[:month].present?
      begin
        @month = Date.parse("#{params[:month]}-01")
      rescue ArgumentError => e
        @month = Date.today
      end
    else
      @month = Date.today
    end

    @transactions = @family_group.transactions
    @category_types = CategoryType.all

    if @month
      start_of_month = @month.beginning_of_month
      end_of_month = @month.end_of_month

      @transactions = @transactions.where(month: start_of_month.strftime("%Y-%m")..end_of_month.strftime("%Y-%m"))
    end

    if params[:category_type].present?
      @category_type = params[:category_type] # Captura o parâmetro enviado
      @transactions = @transactions.joins(transaction_category: :category_type)
        .where(category_types: { name: @category_type })
    end

    @totals_by_category_type = CategoryType.all.each_with_object({}) do |category_type, hash|
      total_value = @transactions.joins(:transaction_category)
                                .where(transaction_categories: { category_type_id: category_type.id })
                                .sum(:value)

      hash[category_type.name] = total_value
    end
  end

  def new_by_category_type
    @category_type = CATEGORY_TYPE_MAP[params[:category_type]]

    if @category_type.nil?
      redirect_to finances_transactions_path(@family_group), alert: "Categoria inválida."
      return
    end

    category_type_key = params[:category_type]
    category_type_name = CATEGORY_TYPE_MAP[category_type_key]
    @transaction_categories = TransactionCategory.joins(:category_type)
      .where(category_types: { name: category_type_name })
      .where(family_group_id: @family_group.id)

    @transaction = @family_group.transactions.build
    @month = params[:month] || Date.today.strftime("%Y-%m")

    respond_to do |format|
      format.turbo_stream { render :new_by_category_type }
      format.html { render :new_by_category_type, layout: false }
    end
  end

  def create
    @transaction = @family_group.transactions.build(transaction_params)

    if @transaction.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append("transactions-body", partial: "transaction", locals: { transaction: @transaction }),
            turbo_stream.remove("modal-frame"),
            turbo_stream.remove("modal")
          ]
        end
        format.html { redirect_to finances_transactions_path(@family_group), notice: "Transação criada com sucesso." }
      end
    else
      Rails.logger.error @transaction.errors.full_messages.join(", ")
      respond_to do |format|
        format.turbo_stream { render :new_by_category_type }
        format.html { render :new_by_category_type }
      end
    end
  end

  def edit
    @transaction = @family_group.transactions.find(params[:id])
    @transaction_categories = TransactionCategory.joins(:category_type)
      .where(category_types: { id: @transaction.transaction_category.category_type_id })
      .order(:name)

    respond_to do |format|
      format.turbo_stream { render :edit }
      format.html { render :edit }
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to finances_transactions_path(@family_group), notice: "Transação atualizada com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @transaction = @family_group.transactions.find(params[:id])

    if @transaction.subscription
      future_transactions = @family_group.transactions.where("month > ? AND name = ? AND transaction_category_id = ? AND bank_account_id = ?", @transaction.month, @transaction.name, @transaction.transaction_category_id, @transaction.bank_account_id)
      future_transactions.destroy_all
    end

    @transaction.destroy
    respond_to do |format|
      format.turbo_stream { redirect_to finances_transactions_path(@family_group), notice: "Transação excluída com sucesso." }
      format.html { redirect_to finances_transactions_path(@family_group), notice: "Transação excluída com sucesso." }
    end
  end

  def destroy_future
    @transaction = @family_group.transactions.find(params[:id])

    if @transaction.subscription
      future_transactions = @family_group.transactions.where("month > ? AND name = ? AND transaction_category_id = ? AND bank_account_id = ?", @transaction.month, @transaction.name, @transaction.transaction_category_id, @transaction.bank_account_id)
      future_transactions.destroy_all
    end

    respond_to do |format|
      format.turbo_stream { redirect_to finances_transactions_path(@family_group), notice: "Faturas futuras excluídas com sucesso." }
      format.html { redirect_to finances_transactions_path(@family_group), notice: "Faturas futuras excluídas com sucesso." }
    end
  end

  private

  def set_and_authorize_family_group
    @family_group = current_user.family_groups.find_by(id: params[:family_group_id])
    unless @family_group
      redirect_to finances_home_path, alert: "Você não tem permissão para acessar este grupo familiar ou ele não existe."
    end
  end

  def set_bank_accounts
    @bank_accounts = @family_group.users.joins(:bank_accounts).select("bank_accounts.*")
  end

  def set_transaction
    @transaction = @family_group.transactions.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(
      :name,
      :value,
      :month,
      :subscription,
      :number_of_installments,
      :current_installment,
      :transaction_category_id,
      :bank_account_id,
      :family_group_id
    )
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/finances/transactions/_form.html.erb
<%= content_tag :h2, 
  class: [
    "text-3xl font-black mb-5 text-gray-500",
  ] do %>  
    <% if @category_type === "Receitas"  %>
      <%= @transaction.new_record? ? "🤑 Nova" : "Editar" %>
      Receita
    <% elsif @category_type === "Investimentos" %>
      <%= @transaction.new_record? ? "🏦 Novo" : "Editar" %>
      Investimento
    <% elsif @category_type === "Gastos Fixos" %>
      <%= @transaction.new_record? ? "🧾 Novo" : "Editar" %>
      Gasto Fixo
    <% else %>
      <%= @transaction.new_record? ? "💳 Novo" : "Editar" %>
      Gasto Variável
    <% end %>
<% end %>

<%= form_with model: [@family_group, @transaction], url: @transaction.new_record? ? create_finances_transaction_path(@family_group) : update_finances_transaction_path(@family_group, @transaction), local: false do |form| %>
  <div class="mb-4">
    <%= form.label :value %>
    <%= 
      form.text_field :value,
      placeholder: "Ex: 800.00",
      class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
    %>
  </div>

  <div class="mb-4">
    <%= form.label :name %>
    <%= 
      form.text_field :name,
      placeholder: "Ex: Compras no Supermercado",
      class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
    %>
  </div>

  <div class="mb-4">
    <%= form.label :month %>
    <%= 
      form.month_field :month,
      value: @month,
      placeholder: "Ex: Janerio 2021",
      class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
    %>
  </div>

  <div class="mb-4">
    <%= form.label :subscription %>
    <%= 
      form.select :subscription,
      options_for_select([["Não", false], ["Sim", true]]),
      { prompt: "Selecione uma opção" },
      class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
    %>
  </div>

  <div class="mb-4">
    <%= form.label :number_of_installments %>
    <%= 
      form.number_field :number_of_installments,
      placeholder: "Ex: 0 para compra única",
      class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
    %>
  </div>

  <div class="mb-4">
    <%= form.label :current_installment %>
    <%= 
      form.number_field :current_installment,
      placeholder: "Ex: 0",
      class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
    %>
  </div>

  <div class="mb-4">
    <%= form.label :bank_account_id %>
    <%= 
      form.collection_select :bank_account_id, @bank_accounts || [], :id, :name,
      { prompt: "Selecione uma conta bancária" },
      { class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" }
    %>
  </div>

  <div class="mb-4">
    <%= form.label :transaction_category_id %>
    <%= 
      form.collection_select :transaction_category_id, @transaction_categories, :id, :name,
      { prompt: "Selecione uma categoria" },
      class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
    %>
  </div>

  <%#= form.hidden_field :transaction_type, value: @category_type %>

  <div class="form-group">
    <%= form.submit @transaction.new_record? ? "Criar Transação" : "Atualizar Transação", class: "w-full bg-blue-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-offset-2" %>
  </div>
<% end %>

app/views/finances/transactions/_hero.html.erb
<div class="hero-card bg-white rounded col-span-12 px-5 py-4 flex items-center">
  <div class="principal-content flex-1">
    <div class="flex text-base text-gray-400 mb-2 gap-1">
      <svg class="w-5 h-6" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-left-right"><path d="M8 3 4 7l4 4"/><path d="M4 7h16"/><path d="m16 21 4-4-4-4"/><path d="M20 17H4"/></svg>
      <p>
        Transações:
      </p>
    </div>
    <h1 class="font-black text-3xl text-gray-700">
      <%= @family_group.name %>
    </h1>
  </div>

  <div class="filter">
    <%= form_with(url: finances_transactions_path(@family_group), method: :get, local: true, data: { turbo_frame: "transactions" }) do |form| %>
      <div class="form-row flex gap-2">
        <div class="col-md-3">
          <%= 
            month_field_tag :month, 
            params[:month], 
            class: "form-control", 
            placeholder: "Selecione o mês", 
            min: "2020-01", 
            max: "2029-12", 
            onchange: "this.form.submit()"
          %>
        </div>
        <div class="col-md-3">
          <%= 
            select_tag :category_type, 
            options_for_select(@category_types.pluck(:name), 
            params[:category_type]), 
            include_blank: "Todas as Categorias", 
            class: "form-control",
            onchange: "this.form.submit()"
          %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/finances/transactions/_total.html.erb
<section class="col-span-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6 mt-6 text-gray-500">
  <% @totals_by_category_type.each do |category_type, total| %>
    <%= link_to new_by_category_type_path(@family_group, new_url(category_type)), data: { turbo_frame: "modal-frame" } do %>
      <div class="relative group overflow-hidden p-8 rounded-xl bg-white border border-gray-200 2border-gray-800 2bg-gray-900 cursor-pointer">
        <div aria-hidden="true" class="inset-0 absolute aspect-video border rounded-full -translate-y-1/2 group-hover:-translate-y-1/4 duration-300 bg-gradient-to-b <%= 'from-green-500' if category_type == "Receitas" %> <%= 'from-blue-500' if category_type == "Investimentos" %> <%= 'from-red-500' if category_type == "Gastos Fixos" %> <%= 'from-yellow-500' if category_type == "Gastos Variáveis" %> to-white 2from-white 2to-white blur-2xl opacity-25 2opacity-5 2group-hover:opacity-10"></div>
        <div class="relative">
          <div class="flex gap-x-2 items-center">
            <div class="border border-green-500/10 flex relative *:relative *:m-auto size-12 rounded-lg 2bg-gray-900 2border-white/15 before:rounded-[7px] before:absolute before:inset-0 before:border-t before:border-white <%= 'before:from-green-100' if category_type == "Receitas" %> <%= 'before:from-blue-100' if category_type == "Investimentos" %> <%= 'before:from-red-100' if category_type == "Gastos Fixos" %> <%= 'before:from-yellow-100' if category_type == "Gastos Variáveis" %> 2before:border-white/20 before:bg-gradient-to-b 2before:from-white/10 2before:to-transparent before:shadow 2before:shadow-gray-950">
              <p class="opacity-100">
                <% if category_type === "Receitas"  %>
                  🤑
                <% elsif category_type === "Investimentos" %>
                  🏦
                <% elsif category_type === "Gastos Fixos" %>
                  🧾
                <% else %>
                  💳
                <% end %>
              </p>
            </div>
            <h2 class="text-xl font-bold">
              <%= category_type %>
            </h2>
          </div>

          <div class="mt-2 pb-3 rounded-b-[--card-border-radius] flex flex-col gap-3">
            <p class="text-4xl font-black <%= 'text-green-400' if category_type == "Receitas" %> <%= 'text-red-400' if category_type != "Receitas" %>">
              <%= category_type != "Receitas" ? "-" : "" %>
              <%= number_to_currency(total, locale: 'pt-BR') %>
            </p>

            <p class="text-gray-700 2text-gray-300 text-xs">
              <% if category_type === "Receitas"  %>
                Receita é o total de ganhos financeiros obtidos em um período específico.
              <% elsif category_type === "Investimentos" %>
                Investimento é a aplicação de recursos visando gerar retorno financeiro futuro.
              <% elsif category_type === "Gastos Fixos" %>
                Gasto fixo é uma despesa recorrente com valor estável, como aluguel ou plano.
              <% else %>
                Gasto variável é uma despesa que muda mensalmente, como lazer ou alimentação.
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/finances/transactions/_transaction.html.erb
<tr id="transaction-<%= transaction.id %>">
  <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
    <p class="text-sm text-gray-600 font-bold">
      <%= transaction.name %>
    </p>
  </td>
  <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
    <%= content_tag :p, 
      class: [
        "text-sm font-normal cursor-pointer text-white rounded inline-block px-2 py-1", 
        transaction.transaction_category.category_type.name == "Receitas" ? "bg-green-400" : "",
        transaction.transaction_category.category_type.name == "Investimentos" ? "bg-blue-400" : "",
        transaction.transaction_category.category_type.name == "Gastos Fixos" ? "bg-red-400" : "",
        transaction.transaction_category.category_type.name == "Gastos Variáveis" ? "bg-yellow-400" : ""
      ] do %>
        <% if transaction.transaction_category.category_type.name == "Receitas"  %>
          🤑
        <% elsif transaction.transaction_category.category_type.name == "Investimentos" %>
          🏦
        <% elsif transaction.transaction_category.category_type.name == "Gastos Fixos" %>
          🧾
        <% else %>
          💳
        <% end %>
        <%= transaction.transaction_category.category_type.name %>
    <% end %>
  </td>
  <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
    <p class="text-sm font-normal text-gray-600 cursor-pointer">
      <%= transaction.transaction_category.name %>
    </p>
  </td>
  <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
    <p class="text-sm font-normal text-gray-600 cursor-pointer">
      <%= transaction.subscription ? "Sim" : "Não" %>
    </p>
  </td>
  <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
    <p class="text-sm font-normal text-gray-600 cursor-pointer">
      <% if transaction.number_of_installments > 0 %>
        <%= transaction.current_installment %> de <%= transaction.number_of_installments %>
      <% else %>
        -  
      <% end %>
    </p>
  </td>
  <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
    <%= content_tag :p, 
      class: [
        "text-sm font-bold cursor-pointer",
        transaction.value < 0 ? "text-red-500" : "text-green-500"
      ] do %>
      <%= number_to_currency(transaction.value) %>
    <% end %>
  </td>
  <td class="px-4 py-2 text-sm font-bold whitespace-nowrap">
    <!-- Ações (editar, excluir, etc.) -->
  </td>
</tr>

app/views/finances/transactions/_transaction_table.html.erb
<section class="col-span-12">
  <div class="flex flex-col mt-0 w-full">
    <div class="overflow-x-auto">
      <div class="inline-block min-w-full align-middle">
        <div class="overflow-hidden border border-gray-200 md:rounded-lg">
          <%= turbo_frame_tag "transactions" do %>
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">Nome</th>
                  <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">Tipo</th>
                  <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">Categoria</th>
                  <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">Parcelado</th>
                  <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">Parcela</th>
                  <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">Valor</th>
                  <th scope="col" class="px-4 py-3.5  text-sm font-black text-left rtl:text-right text-gray-500">Ações</th>
                </tr>
              </thead>
              <tbody id="transactions-body" class="bg-white divide-y divide-gray-200">
                <% if @transactions.any? %>
                  <% @transactions.each do |transaction| %>
                    <%= render partial: "transaction", locals: { transaction: transaction } %>
                  <% end %>
                <% else %>
                  <tr>
                    <td colspan="7" class="px-4 py-10 text-sm font-bold text-center text-gray-600">
                      Nenhuma transação encontrada para o período selecionado.
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/finances/transactions/edit.html.erb
<%= turbo_frame_tag "modal-frame" do %>
  <div class="modal">
    <div class="modal-content">
      <%= render 'form', transaction: @transaction %>
    </div>
  </div>
<% end %>

app/views/finances/transactions/index.html.erb
<!-- Confirmation Modal -->
<div id="delete-confirmation-modal" class="modal hidden fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50 pb-20">
  <div class="modal-content bg-white rounded-lg p-6 mx-auto mt-20 w-1/3">
    <h2 class="text-xl font-bold mb-4">Confirmar Exclusão</h2>
    <p class="mb-4">Você deseja excluir apenas as faturas futuras ou todas as faturas?</p>
    <div class="flex justify-end">
      <button id="delete-future-only" class="bg-red-500 text-white px-4 py-2 rounded mr-2">Excluir Faturas Futuras</button>
      <button id="delete-all" class="bg-red-700 text-white px-4 py-2 rounded">Excluir Todas as Faturas</button>
      <button id="cancel-delete" class="bg-gray-300 text-black px-4 py-2 rounded ml-2">Cancelar</button>
    </div>
  </div>
</div>

<div class="individual-content grid gap-x-3	grid-cols-12">
  <%= render 'hero' %>

  <%= render 'total' %>

  <%= render 'transaction_table' %>
</div>

app/views/finances/transactions/new_by_category_type.html.erb
<%= turbo_frame_tag "modal-frame" do %>
  <div class="modal z-50">
    <div class="modal-content">
      <%= render 'form' %>
    </div>
  </div>
<% end %>

app/views/finances/transactions/new_by_category_type.turbo_stream.erb
<%= turbo_frame_tag "modal-frame" do %>
  <div class="modal z-50">
    <div class="modal-content">
      <%#= render 'form' %>
    </div>
  </div>
<% end %>

app/views/finances/transactions/show.html.erb
<h2>Detalhes da Transação</h2>

<p><strong>Descrição:</strong> <%= @transaction.description %></p>
<p><strong>Categoria:</strong> <%= @transaction.transaction_category.name %></p>
<p><strong>Valor:</strong> <%= number_to_currency(@transaction.amount) %></p>
<p><strong>Data:</strong> <%= @transaction.date.strftime("%d/%m/%Y") %></p>

<%= link_to "Voltar", finances_family_group_transactions_path(@family_group), class: "btn btn-secondary" %>