config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/finances")
  devise_for :users

  # Finances Routes - Home
  get "/finances", to: "finances/home#index", as: "finances_home"

  resources :family_groups, only: [ :index, :new, :create ] do
    post :add_user, on: :member
  end

  # Dashboard
  get "/finances/:family_group_id/dashboard", to: "finances/dashboards#show", as: "finances_dashboard"

  # Budgets Routes
  get "/finances/:family_group_id/budgets", to: "finances/budgets#index", as: "finances_budgets"
  get "/finances/:family_group_id/budget/new", to: "finances/budgets#new", as: "new_finances_budget"
  get "/finances/:family_group_id/budget/edit", to: "finances/budgets#edit", as: "edit_finances_budgets"
  patch "/finances/:family_group_id/budget/update/:month", to: "finances/budgets#update", as: "update_for_month"
  get "/finances/:family_group_id/budget/:month", to: "finances/budgets#show", as: "finances_budget_show"
  post "/finances/:family_group_id/budget", to: "finances/budgets#create", as: "create_finances_budget"

  # Consolidated Routes
  get "/finances/:family_group_id/consolidated", to: "finances/consolidated#index", as: "finances_consolidated"

  # Transactions Routes
  get "/finances/:family_group_id/transactions", to: "finances/transactions#index", as: "finances_transactions"
  get "/finances/:family_group_id/transactions/new/:category_type", to: "finances/transactions#new_by_category_type", as: "new_by_category_type"
  post "/finances/:family_group_id/transactions", to: "finances/transactions#create", as: "create_finances_transaction"
  get "/finances/:family_group_id/transactions/:id/edit", to: "finances/transactions#edit", as: "edit_finances_transaction"
  patch "/finances/:family_group_id/transactions/:id", to: "finances/transactions#update", as: "update_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id", to: "finances/transactions#destroy", as: "destroy_finances_transaction"
  delete "/finances/:family_group_id/transactions/:id/destroy_future", to: "finances/transactions#destroy_future", as: "destroy_future_finances_transaction"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Finances On Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-200 flex">
    <%= render SidebarComponent.new(current_user: current_user, family_group: @family_group) %>

    <main class="content w-full px-5 py-5">
      <% if flash[:alert] %>
        <div
          class="font-regular relative block w-full rounded-lg bg-red-500 p-4 text-base leading-5 text-white opacity-100 mb-5"
          data-dismissible="alert"
        >
          <div class="mr-12"><%= flash[:alert] %></div>
          <div class="absolute top-2.5 right-3 w-max rounded-lg transition-all hover:bg-white hover:bg-opacity-20" data-dismissible-target="alert">
            <%= link_to root_path do %>
              <button
                role="button"
                class="w-max rounded-lg p-1"
                data-alert-dimissible="true"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M6 18L18 6M6 6l12 12"
                  ></path>
                </svg>
              </button>
            <% end %>
          </div>
        </div>
      <% end %>

      <% if flash[:notice] %>
        <div
          class="font-regular relative block w-full rounded-lg bg-green-500 p-4 text-base leading-5 text-white opacity-100 mb-5"
          data-dismissible="notice"
        >
          <div class="mr-12"><%= flash[:notice] %></div>
          <div class="absolute top-2.5 right-3 w-max rounded-lg transition-all hover:bg-white hover:bg-opacity-20" data-dismissible-target="alert">
            <button
              role="button"
              class="w-max rounded-lg p-1"
              data-alert-dimissible="true"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M6 18L18 6M6 6l12 12"
                ></path>
              </svg>
            </button>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <div id="modal" class="modal fixed inset-0 overflow-hidden backdrop-blur-sm flex items-center justify-end pr-3 py-3 transition-transform duration-300 transform translate-x-full z-50 hidden">
      <%= turbo_frame_tag "modal-frame", class: "modal-content p-6 bg-white w-11/12 sm:w-11/12 md:w-7/12 lg:w-5/12 rounded-xl shadow-lg h-full overflow-y-auto overflow-hidden border border-gray-100" do %>
      <% end %>
    </div>

    <% unless current_page?(finances_home_path) %>
      <div class="fixed right-3 bottom-3 inline-block text-left">
        <div class="relative">
          <div id="dropdown-transactions" class="absolute right-0 z-10 -mt-40 w-44 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black/5 focus:outline-none hidden" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1 text-right" role="none">
              <%= link_to "Nova Receita", new_by_category_type_path(@family_group, new_url("Receitas")), data: { turbo_frame: "modal-frame" }, class: "block px-4 py-2 text-sm text-gray-700 font-medium hover:text-green-600 hover:bg-gray-100", role: "menuitem", tabindex: "-1", id: "menu-item-0" %>
              <%= link_to "Novo Investimento", new_by_category_type_path(@family_group, new_url("Investimentos")), data: { turbo_frame: "modal-frame" }, class: "block px-4 py-2 text-sm text-gray-700 font-medium hover:text-blue-600 hover:bg-gray-100", role: "menuitem", tabindex: "-1", id: "menu-item-1" %>
              <%= link_to "Novo Gasto Fixo", new_by_category_type_path(@family_group, new_url("Gastos Fixos")), data: { turbo_frame: "modal-frame" }, class: "block px-4 py-2 text-sm text-gray-700 font-medium hover:text-red-600 hover:bg-gray-100", role: "menuitem", tabindex: "-1", id: "menu-item-2" %>
              <%= link_to "Novo Gasto Variável", new_by_category_type_path(@family_group, new_url("Gastos Variáveis")), data: { turbo_frame: "modal-frame" }, class: "block px-4 py-2 text-sm text-gray-700 font-medium hover:text-yellow-600 hover:bg-gray-100", role: "menuitem", tabindex: "-1", id: "menu-item-3" %>
            </div>
          </div>

          <button id="button-add-transaction" class="fab-button p-0 w-16 h-16 bg-blue-600 rounded-full hover:bg-blue-700 mouse shadow-xl transition ease-in duration-200 focus:outline-none">
            <svg viewBox="0 0 20 20" enable-background="new 0 0 20 20" class="w-6 h-6 inline-block">
              <path fill="#FFFFFF" d="M16,10c0,0.553-0.048,1-0.601,1H11v4.399C11,15.951,10.553,16,10,16c-0.553,0-1-0.049-1-0.601V11H4.601 C4.049,11,4,10.553,4,10c0-0.553,0.049-1,0.601-1H9V4.601C9,4.048,9.447,4,10,4c0.553,0,1,0.048,1,0.601V9h4.399 C15.952,9,16,9.447,16,10z" />
            </svg>
          </button>

          <div id="bg-dropdown" class="w-screen h-screen bg-black fixed top-0 right-0 opacity-0 z-0 hidden"></div>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Finances On Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>